### ISSUE TITLE
 this._smartglass._console.get_requestnum is not a function

### ISSUE THREAD

**Issue by WestCoast5550** [unknownskl/homebridge-smartglass#10]
TypeError: this._smartglass._console.get_requestnum is not a function
    at Object.<anonymous> (/homebridge/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/channels/systeminput.js:42:47)
    at EventEmitter.emit (events.js:203:15)
    at EventEmitter.<anonymous> (/homebridge/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/events.js:112:23)
    at EventEmitter.emit (events.js:198:13)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-smartglass/node_modules/xbox-smartglass-core-node/src/smartglass.js:234:33)
    at Socket.emit (events.js:198:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)

It looks like it should be like that:)

**Comment by unknownskl** [comment]
Please try the new 0.13 update. It fixes a lot of errors related to this.

**Comment by WestCoast5550** [comment]
Thank you very much for your work!
