### ISSUE TITLE
Unable to Setup Xbox

### ISSUE THREAD

**Issue by MrRizzles** [unknownskl/homebridge-smartglass#17]
ReferenceError: error is not defined
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:188:40)
    at EventEmitter.emit (events.js:323:22)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/events.js:116:27)
    at EventEmitter.emit (events.js:311:20)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:264:30)
    at Socket.emit (events.js:311:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)

**Comment by unknownskl** [comment]
Error looks related to the plugin homebridge-xbox-tv, not smartglass-homebridge. Closing the issue.
